### ISSUE TITLE
Issues are not shown

### ISSUE THREAD

**Issue by gercograndia** [pdsoftplan/sonar-zap#2]
When clicking through on the reported issues, the total number of issues found is shown, but no detailed result.

![image](https://cloud.githubusercontent.com/assets/432439/15611957/12b95348-242d-11e6-8f92-222c1941422e.png)

**Comment by tfcporciuncula** [comment]
Unfortunately, that's how the plugin works. It simply keeps track of the number of alerts and if you need more detailed information, you have to look at ZAP's report.

We've stopped working to improve the integration because at the time we were writing the plugin, another one came out. It treats ZAP alerts as regular SonarQube issues and you can actually see information about each alert identified, just as you'd like to.

Although this is definitely a more complete solution, It's also more intrusive because the number of issues reported by SonarQube will also include the number of ZAP alerts. If you already have quality gates with rules based on the number of issues, like we did, you might not want that. That's why we decided to keep our plugin the way it is, to provide a simpler alternative.

We should probably make this clear on our README, and you should probably try the other plugin!
https://github.com/stevespringett/zap-sonar-plugin

**Comment by gercograndia** [comment]
Thanks and fair enough, just not what I expected. I'll have a look at the alternative, and thanks for the effort anyway!!!
